Fix "AttributeError class Config has no attribute 'destory'" because the plugin IDAtropy has the same class name Config
![image](https://user-images.githubusercontent.com/526959/57905456-d549e100-78a0-11e9-9aa2-b8defed4041a.png)