Fix namespace pollution error "AttributeError class Config has no attribute 'destory'" because the plugin IDAtropy has the same class name Config
Fix namespace pollution error "AttributeError class Config has no attribute 'destory'" because the plugin IDAtropy has the same class name Config.
A similar error: https://github.com/igogo-x86/HexRaysPyTools/issues/19